# frozen_string_literal: true

source "https://rubygems.org"

# https://github.com/jekyll/jekyll/issues/9233#issuecomment-1367756669
ruby '3.1.3'

# Fix: https://github.com/jekyll/jekyll/issues/8523
gem 'webrick', '~> 1.7'

gem "jekyll", "~> 3.9.2"
gem "jekyll-theme-architect"
gem "jekyll-redirect-from"

group :jekyll_plugins do
#  https://rubygems.org/gems/github-pages
    gem "github-pages", "~> 227"
    gem "jekyll-twitter-plugin"
    gem "jekyll-toc"
end 
